repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-json
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.6"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: "0.0.2"
    hooks:
      - id: stylelint
        additional_dependencies:
          - stylelint
          - stylelint-config-standard-scss
